[build]
  # Directory to change to for package.json before starting a build.
  base = "/"

  # Directory that contains the deploy-ready HTML files
  publish = "client"

  # Default build command.
  command = "npm run build"

[[redirects]]
  from = "/api/current-conditions/"
  to = "https://api.openweathermap.org/data/2.5/weather?q=:q&units=imperial&APPID=OPENWEATHER_API_KEY_REPLACE"
  query = {q = ":q"}
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/uvi/"
  to = "https://api.openweathermap.org/data/2.5/uvi?lat=:lat&lon=:lon&APPID=OPENWEATHER_API_KEY_REPLACE"
  query = {lat = ":lat", lon = ":lon"}
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/five-day/"
  to = "https://api.openweathermap.org/data/2.5/forecast?q=:q&units=imperial&APPID=OPENWEATHER_API_KEY_REPLACE"
  query = {q = ":q"}
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/get-unsplash"
  to = "https://api.unsplash.com/search/photos?query=:query&client_id=UNSPLASH_API_KEY_REPLACE"
  query = {query = ":query"}
  status = 200
  force = true
  headers = {X-From = "Netlify"}
